version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pinterest-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v3j6e64m3mrb"
s3_prefix = "pinterest-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
